"""Canonical reproduction entry point: `python -m stated_vs_revealed.reproduce`.

Runs the test suite, then analyze.py for every registered env against every
run directory under results/live/<env>/, and writes results/summary.md +
results/summary.json. Verification against the checked-in golden file is a
JSON diff (`git diff --exit-code results/summary.json`), never a diff
against prose -- see docs/findings.md for why (a prose diff invites
"looks close enough" instead of an exact match).

scripts/reproduce.sh is only a one-line wrapper around this module; put no
logic there.
"""

from __future__ import annotations

import importlib.util
import json
import subprocess
import sys
from pathlib import Path

from stated_vs_revealed.analyze import analyze
from stated_vs_revealed.envs import ENVS

REPO_ROOT = Path(__file__).resolve().parents[2]


def _prereg_path_for_run(env_name: str, run_dir: Path) -> Path:
    config_used = json.loads((run_dir / "config_used.json").read_text(encoding="utf-8"))
    return REPO_ROOT / config_used["prereg_file"]


def run_tests() -> bool:
    """True means "proceed to regenerate the summary" -- either the tests
    actually passed, or pytest isn't installed at all (`pip install -e .`
    without the `[dev]` extra). The second case is loudly warned about, not
    silently treated as a red suite: a missing test runner and a failing
    test suite are different problems with different fixes, and collapsing
    them into one "Tests failed" message sends someone to debug tests that
    never ran."""
    if importlib.util.find_spec("pytest") is None:
        print(
            "WARNING: pytest is not installed -- skipping the test suite. "
            'Install it with `pip install -e ".[dev]"` to run tests before '
            "trusting a regenerated summary."
        )
        return True
    result = subprocess.run([sys.executable, "-m", "pytest", "tests/", "-q"], cwd=REPO_ROOT)
    return result.returncode == 0


def regenerate_summary() -> dict:
    summary: dict = {}
    for env_name in sorted(ENVS):
        env_root = REPO_ROOT / "results" / "live" / env_name
        if not env_root.exists():
            continue
        run_results = []
        for run_dir in sorted(env_root.iterdir()):
            if not run_dir.is_dir() or not (run_dir / "config_used.json").exists():
                continue
            prereg_path = _prereg_path_for_run(env_name, run_dir)
            if not prereg_path.exists():
                # A missing prereg is a real problem with this run directory
                # (its config_used.json points at a file that isn't there),
                # not something to silently drop from the summary -- record
                # it as an error so main() can fail loudly on it, same as
                # any other analysis exception.
                result = {"error": f"FileNotFoundError: prereg_file {prereg_path} does not exist"}
            else:
                prereg = json.loads(prereg_path.read_text(encoding="utf-8"))
                try:
                    result = analyze(env_name, run_dir, prereg)
                except Exception as e:  # noqa: BLE001 - a failed run dir is data, not a crash
                    result = {"error": f"{type(e).__name__}: {e}"}
            run_results.append({"run": run_dir.name, **result})
        summary[env_name] = run_results
    return summary


def write_summary(summary: dict) -> None:
    (REPO_ROOT / "results" / "summary.json").write_text(json.dumps(summary, indent=2, default=str), encoding="utf-8")

    lines = ["# Results summary", "", "Generated by `python -m stated_vs_revealed.reproduce`. Never hand-edited.", ""]
    for env_name, runs in summary.items():
        lines.append(f"## {env_name}")
        for run in runs:
            lines.append(f"### {run['run']}")
            if run.get("error"):
                lines.append(f"- ERROR: {run['error']}")
                continue
            for arm, (s, n) in run.get("counts", {}).items():
                rate = f"{s}/{n} ({s/n*100:.1f}%)" if n else "n=0"
                lines.append(f"- Arm {arm}: {rate}")
            if run.get("test"):
                t = run["test"]
                lines.append(f"- diff = {t['diff_pp']:.1f}pp, p_value_primary = {t['p_value_primary']:.3f} ({t['primary_hypothesis_direction']})")
            elif run.get("note"):
                lines.append(f"- {run['note']}")
            if run.get("secondary"):
                sec = run["secondary"]
                lines.append(f"- secondary ({', '.join(sec['instrument'])}, never primary): " + ", ".join(
                    f"{arm} {s}/{n} ({s/n*100:.1f}%)" for arm, (s, n) in sec.get("counts", {}).items()
                ))
                if "diff_pp" in sec:
                    lines.append(f"  diff = {sec['diff_pp']:.1f}pp, p_two_sided = {sec['p_value_two_sided']:.3f}")
        lines.append("")
    (REPO_ROOT / "results" / "summary.md").write_text("\n".join(lines) + "\n", encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    if not run_tests():
        print("Tests failed -- not regenerating summary from a red test suite.")
        return 1
    summary = regenerate_summary()
    write_summary(summary)
    print(json.dumps(summary, indent=2, default=str))
    print("\nWrote results/summary.json and results/summary.md.")
    print("Verify with: git diff --exit-code results/summary.json")

    errors = [
        f"{env_name}/{run['run']}: {run['error']}"
        for env_name, runs in summary.items()
        for run in runs
        if run.get("error")
    ]
    if errors:
        print(f"\n{len(errors)} run(s) failed to analyze -- summary.json/md still written, but this is not a clean reproduce:")
        for e in errors:
            print(f"  - {e}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
